# Define variables
NODE_ENV = development
NODE_PORT = 5144
NODE_APP = index.js

# Makefile pour mapper les boutons du contrôleur NES
.PHONY: bouton_a bouton_b bouton_start bouton_select

bouton_a:
	@echo "Compiling project 📚"&

bouton_b:
	@echo "✨ Generation du Prompt en Cours ✨ ... "


bouton_start:
	@echo "Starting the server A..."

bouton_select:
	@echo "💫 " &
	@echo "  ╔═══════════════════════════════════════════════════════════════════════════╗"&
	@echo "  ║ [💫] [💻] [📱] [💬] [🔷] [🧾] [💳] [💾]                                [🛰]║"&
	@echo "  ╠═══════════════════════════════════════════════════════════════════════════╣"&
	@echo "  ║                                                                           ║"&
	@echo "  ║                     💫 # Welcom NeoFs - Ia # 🤗                           ║"&
	@echo "  ║                                                                           ║"&
	@echo "  ║                                                                           ║"&
	@echo "  ║            [1] - Star serveur                                             ║"&
	@echo "  ║            [2] - Run _Pibot_                                              ║"&
	@echo "  ║            [3] - Brainstroming                                            ║"&
	@echo "  ║            [4] - Chatbot                                                  ║"&
	@echo "  ║            [5] - MyPrompt                                                 ║"&
	@echo "  ║            [6] - HowTo                                                    ║"&
	@echo "  ║            [7] - Build Composant                                          ║"&
	@echo "  ║            [8] - Compose Page                                             ║"&
	@echo "  ║            [9] - Update                                                   ║"&
	@echo "  ║           [10] - Exit                                                     ║"&
	@echo "  ║                                                                           ║"&
	@echo "  ║                                                                           ║"&
	@echo "  ║                                                                           ║"&
	@echo "  ╠═══════════════════════════════════════════════════════════════════════════╣"&
	@echo "  ║[🌴.✨]:/<                                                             /📡>║"&
	@echo "  ╚═══════════════════════════════════════════════════════════════════════════╝"&
	@echo ""&


all: $(MAGIC_TARGETS)

update:
	@echo "✨ Mise en état du dossier sur github✨"
	@git add .
	@git commit -m "test"
	@git push
	@echo "✨ Mise à jour terminée✨"

init: gantt phase1 phase2 phase3 phase4 phase5 phase6 phase7 phase8
# Magic COMPILER groq quantum
gantt:
	@echo "initialisation de l'instance"
	@git clone auto

phase1:
	@echo "phase de conception"
	@node mission.js

phase2:
	@echo "phase de configuration"
	@node configuration.js

phase3:
	@echo "phase d'entrainnement du model IA"
	@node models.js

phase4:
	@echo "phase de gestion et iteration du frontend"
	@git clone src.js
	
phase5:
	@echo "phase de gestion et iteration du backend"
	@node srv.js


phase6:
	@echo "phase de test et debugage"
	@node data.js

phase7:
	@echo "phase de validation documentation"
	@node models/modelcss.js

phase8:
	@echo "phase d'affiliation et contribution"
	@node models/modelcss.js

server:
	@node srv/Telegram/server.js
	@echo "Unleashing quantum Magic Mafile with every script we shape" 
# Ouvrez-vous aux dimensions cachées
clean-r:
	@echo "Returning the quantum realm to pristine state"
	@rm -rf data/* build/* src/* data/*

clean-R:
	@echo "Unweaving the fabric, a celestial fate"@rm -rf output/ build/ src/ data/

clean: clean-r clean-R